---
filepath: ""
environments:
  default:
    values:
      - values.yaml
---
namespace: dev-namespace
releases:
  - name: bug-tracker
    chart: oci://ghcr.io/nimesha-premaraja/bug-tracker/helm-charts/bug-tracker     
    version: 0.1.0
    installed: true
    values:
      - values.yaml
templates: {}
renderedvalues: {}