apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - env:
        - name: chart-version
          value: 0.1.1
        - name: component
          value: app
        - name: namespace
          value: dev-namespace
        image: ghcr.io/nimeshadil/backend:latest
        name: backend
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: '1.5'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 1.5Gi
