apiVersion: v1
data:
  FLASK_APP: wsgi.py
  FLASK_ENV: production
  UPLOAD_FOLDER: /app/app/uploads
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: bug-tracker
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bug-tracker-bug-tracker
    app.kubernetes.io/version: 0.1.0
  name: bug-tracker-bug-tracker-config
  namespace: bug-tracker
