apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: bug-tracker
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bug-tracker-bug-tracker
    app.kubernetes.io/version: 0.1.0
  name: bug-tracker-bug-tracker
  namespace: dev-namespace
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: bug-tracker-bug-tracker
  type: ClusterIP
