apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    app.kubernetes.io/instance: bug-tracker
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: bug-tracker-bug-tracker
    app.kubernetes.io/version: 0.1.0
  name: bug-tracker-bug-tracker-pdb
  namespace: bug-tracker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: bug-tracker-bug-tracker
