apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - env:
        - name: chart-version
          value: 0.1.0
        - name: component
          value: app
        - name: namespace
          value: dev-namespace
        image: ghcr.io/nimeshadil/frontend:latest
        name: frontend
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: '1.5'
            memory: 2Gi
          requests:
            cpu: '1'
            memory: 1.5Gi
